#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# with local npm installation
# npm run lint
# npm test

# with docker development environment
docker exec -i ng-container sh -c "cd demo-app && npm run lint"
docker exec -i ng-container sh -c "cd demo-app && npm test"
